'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '@/lib/api';
import { getToken } from '@/lib/auth';

export default function ScheduleImportPage() {
  const [token,setToken]=useState(''); const [seasons,setSeasons]=useState<any[]>([]); const [seasonId,setSeasonId]=useState('');
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<any>(null); const [result,setResult]=useState<any>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>setToken(getToken() || ''),[]);
  useEffect(()=>{if(!token)return;apiFetch('/seasons?page_size=100',{},token).then((x:any)=>{const rows=x.items||x; setSeasons(rows); setSeasonId(rows.find((s:any)=>s.is_active)?.id||rows[0]?.id||'');}).catch((e:any)=>setError(e.message));},[token]);
  const upload=async()=>{if(!file||!seasonId)return; setBusy(true);setError('');const body=new FormData();body.append('file',file);try{setPreview(await apiFetch(`/schedule-imports/preview?season_id=${seasonId}`,{method:'POST',body},token));}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const confirm=async()=>{setBusy(true);setError('');try{setResult(await apiFetch(`/schedule-imports/${preview.import_id}/confirm`,{method:'POST',body:JSON.stringify({confirmation:'Replace Existing Schedule Games'})},token));setPreview(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  if(result)return <div className='space-y-4'><h1 className='text-2xl font-bold'>Schedule Import Completed</h1><div className='rounded border bg-emerald-50 p-4'><strong>{result.games_imported} games imported successfully.</strong><p>Weeks replaced: {result.weeks_replaced.map((x:number)=>`Week ${x}`).join(', ')}</p><p>{result.existing_games_removed} existing games were removed. {result.warning_count} warnings.</p></div><div className='flex gap-3'><Link className='rounded bg-blue-700 px-4 py-2 text-white' href='/admin/manual-schedule-builder'>View Imported Schedule</Link><button className='rounded border px-4 py-2' onClick={()=>setResult(null)}>Import Another File</button></div></div>;
  return <div className='space-y-5'><div><h1 className='text-2xl font-bold'>Import Schedule</h1><p className='text-sm text-slate-600'>Upload CSV or XLSX. Uploading only validates and stages data; it never changes the active schedule.</p></div>{error&&<div className='rounded border border-red-300 bg-red-50 p-3 text-red-800'>{error}</div>}
  {!preview&&<div className='rounded border bg-white p-4 space-y-3'><h2 className='font-semibold'>1. Upload and validate</h2><select className='block rounded border p-2' value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input type='file' accept='.csv,.xlsx' onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||busy} className='block rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50' onClick={upload}>{busy?'Validating…':'Validate and Preview'}</button></div>}
  {preview&&<><div className='grid gap-3 sm:grid-cols-3 lg:grid-cols-6'>{[['Rows',preview.rows_uploaded],['Valid games',preview.valid_games],['Invalid rows',preview.invalid_rows],['Weeks',preview.weeks.join(', ')],['Existing replaced',preview.existing_games_to_replace],['Dates',`${preview.earliest_date} – ${preview.latest_date}`]].map(([a,b])=><div key={String(a)} className='rounded border bg-white p-3 text-sm'><div className='text-slate-500'>{a}</div><strong>{b}</strong></div>)}</div>
  {preview.is_full_regular_season&&<div className='rounded border border-amber-400 bg-amber-50 p-3 font-semibold'>This import will replace the entire existing regular-season schedule.</div>}
  <div className='overflow-x-auto rounded border bg-white'><table className='min-w-full text-sm'><thead className='bg-slate-100'><tr>{['Row','Week','Date','Kickoff','Site','Field','Division','Home Team','Away Team','Status','Message'].map(h=><th className='p-2 text-left' key={h}>{h}</th>)}</tr></thead><tbody>{preview.rows.map((r:any)=><tr className='border-t' key={r.row}>{[r.row,r.week,r.date,r.kickoff,r.site,r.field,r.division,r.home_team,r.away_team,r.status,r.message].map((v:any,i:number)=><td className={`p-2 ${i===9?(r.status==='ERROR'?'font-bold text-red-700':'font-bold text-emerald-700'):''}`} key={i}>{v}</td>)}</tr>)}</tbody></table></div>
  <div className='rounded border-2 border-amber-400 bg-amber-50 p-4 space-y-2'><h2 className='text-lg font-bold'>Schedule Replacement Confirmation</h2><p>This import contains games for {preview.weeks.map((x:number)=>`Week ${x}`).join(', ')}.</p><p>Existing games for only these imported weeks will be permanently replaced. Other schedule weeks will not be changed.</p><p><strong>Existing games to be removed: {preview.existing_games_to_replace}</strong><br/><strong>Imported games to be created: {preview.games_to_add}</strong></p><div className='flex gap-3'><button disabled={preview.blocking_errors>0||busy} onClick={confirm} className='rounded bg-red-700 px-4 py-2 font-semibold text-white disabled:opacity-50'>Replace Existing Schedule Games</button><button className='rounded border bg-white px-4 py-2' onClick={()=>setPreview(null)}>Cancel Import</button></div>{preview.blocking_errors>0&&<p className='text-red-700'>Correct all blocking errors before confirmation.</p>}</div></>}
  </div>;
}
