import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const organizationsSource = readFileSync(new URL('../src/app/(dashboard)/admin/organizations/page.tsx', import.meta.url), 'utf8');
const scheduleSource = readFileSync(new URL('../src/app/schedule/page.tsx', import.meta.url), 'utf8');
const standingsSource = readFileSync(new URL('../src/app/(dashboard)/admin/standings/page.tsx', import.meta.url), 'utf8');
const scheduleManagementSource = readFileSync(new URL('../src/app/(dashboard)/admin/schedule-management/page.tsx', import.meta.url), 'utf8');
const bracketSource = readFileSync(new URL('../src/components/TournamentBracket.tsx', import.meta.url), 'utf8');
const logoSource = readFileSync(new URL('../src/components/CommunityLogo.tsx', import.meta.url), 'utf8');

assert.match(organizationsSource, /Community Logo/);
assert.match(organizationsSource, /File type: PNG only/);
assert.match(organizationsSource, /Maximum file size: 2 MB/);
assert.match(organizationsSource, /Minimum size: 500 × 500 pixels/);
assert.match(organizationsSource, /accept='image\/png,\.png'/);
assert.match(organizationsSource, /Upload PNG Logo/);
assert.match(organizationsSource, /Replace Logo/);
assert.match(organizationsSource, /Remove Logo/);
assert.match(organizationsSource, /Only PNG logo files are accepted\./);
assert.match(organizationsSource, /Logo file must be 2 MB or smaller\./);
assert.match(organizationsSource, /logo_uploaded_at/);
assert.match(organizationsSource, /Logo metadata exists, but the logo image URL is missing\./);
assert.match(organizationsSource, /Logo image could not be loaded\. Please replace the logo or check storage configuration\./);
assert.match(organizationsSource, /setItems\(\(current\) => current\.map/);
assert.match(scheduleSource, /home_team_logo_url/);
assert.match(scheduleSource, /away_team_logo_url/);
assert.match(scheduleSource, /<CommunityLogo src=\{g\.home_team_logo_url\}/);
assert.match(scheduleSource, /home_team_community_name/);
assert.match(scheduleSource, /home_team_logo_alt_text/);
assert.match(standingsSource, /community_logo_url/);
assert.match(standingsSource, /<CommunityLogo src=\{row\.community_logo_url\}/);
assert.match(scheduleManagementSource, /home_team_logo_url/);
assert.match(scheduleManagementSource, /away_team_logo_url/);
assert.match(bracketSource, /team_1_logo_url/);
assert.match(bracketSource, /team_2_logo_url/);
assert.match(bracketSource, /<CommunityLogo src=\{teamLogoUrl\(game, slot\)\}/);
assert.match(bracketSource, /<image href=/);
assert.match(logoSource, /object-contain/);
assert.match(logoSource, /onError/);
assert.match(logoSource, /setFailedSrc/);
assert.match(logoSource, /onLoadError/);
assert.match(logoSource, /logo fallback/);
assert.match(organizationsSource, /const deleted = await apiFetch\(`\/organizations\/\$\{deleteTarget\.id\}`/);
assert.match(organizationsSource, /deleted\?\.is_active !== false \|\| !deleted\?\.deleted_at/);
assert.doesNotMatch(organizationsSource, /setItems\(\(current\) => current\.filter/);
assert.match(organizationsSource, /canDeleteOrganizations = isLeagueAdmin \|\| isSchedulingAdmin/);
assert.match(organizationsSource, /Historical games, scores, tournaments, and logo metadata are preserved\./);
