'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { getAuthUser, getToken } from '@/lib/auth';
import { formatDisplayDate, formatDisplayTime } from '@/lib/displayFormat';
const initialForm = { season_id:'', week_id:'', division_id:'', home_team_id:'', away_team_id:'', field_id:'', game_status_id:'', game_date:'', kickoff_time:'' };
export default function GamesPage(){const user=getAuthUser(); const isCommunityAdmin=user?.role_name==='COMMUNITY_ADMIN'; const [games,setGames]=useState<any[]>([]); const [form,setForm]=useState<any>(initialForm); const [editingId,setEditingId]=useState<string|undefined>(); const [validation,setValidation]=useState<any>(); const [filters,setFilters]=useState<Record<string,string>>({}); const [refs,setRefs]=useState<any>({seasons:[],weeks:[],divisions:[],teams:[],fields:[],statuses:[]});
const loadRefs=async()=>{const t=getToken(); const [seasons,weeks,divisions,teams,fields,statuses]=await Promise.all([apiFetch('/seasons',{},t),apiFetch('/weeks',{},t),apiFetch('/divisions',{},t),apiFetch('/teams',{},t),apiFetch('/fields',{},t),apiFetch('/game-statuses',{},t)]); setRefs({seasons:seasons.items,weeks:weeks.items,divisions:divisions.items,teams:teams.items,fields:fields.items,statuses:statuses.items});};
const loadGames=async()=>{const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>Boolean(v))) as Record<string,string>; const q=new URLSearchParams(params); const d=await apiFetch(`/games?${q.toString()}`,{},getToken()); setGames(d.items||[]);}; useEffect(()=>{loadRefs(); loadGames();},[]);
const save=async()=>{const path=editingId?`/games/${editingId}`:'/games'; const method=editingId?'PUT':'POST'; try{const res=await apiFetch(path,{method,body:JSON.stringify(form)},getToken()); setValidation(res.validation); setForm(initialForm); setEditingId(undefined); loadGames();} catch(e:any){setValidation({hard_conflicts:[{code:'save_error',message:e.message}],soft_warnings:[]});}};
return <div className='space-y-4'><h1 className='text-2xl font-bold'>{isCommunityAdmin ? 'League Schedule' : 'Manual Game Schedule Builder'}</h1><div className='grid gap-2 md:grid-cols-5'>{['division_id','week_id','team_id','host_location_id','status_code'].map((k)=><input key={k} placeholder={`Filter ${k}`} className='rounded border p-2' value={filters[k]||''} onChange={e=>setFilters({...filters,[k]:e.target.value})}/>)}<button className='rounded bg-slate-700 px-3 py-2 text-white' onClick={loadGames}>Apply filters</button></div>{!isCommunityAdmin && <div className='grid gap-2 rounded border p-3 md:grid-cols-2'><input type='date' className='rounded border p-2' value={form.game_date} onChange={e=>setForm({...form,game_date:e.target.value})}/><input type='time' className='rounded border p-2' value={form.kickoff_time} onChange={e=>setForm({...form,kickoff_time:e.target.value})}/>{[['season_id',refs.seasons,'name'],['week_id',refs.weeks,'week_number'],['division_id',refs.divisions,'name'],['home_team_id',refs.teams,'name'],['away_team_id',refs.teams,'name'],['field_id',refs.fields,'name'],['game_status_id',refs.statuses,'label']].map(([k,list,label])=><select key={k as string} className='rounded border p-2' value={form[k as string]} onChange={e=>setForm({...form,[k]:e.target.value})}><option value=''>{k as string}</option>{(list as any[]).map(o=><option key={o.id} value={o.id}>{o[label as string]}</option>)}</select>)}<div className='md:col-span-2 flex gap-2'><button className='rounded bg-emerald-700 px-4 py-2 text-white' onClick={save}>{editingId?'Update':'Create'}</button></div></div>}{validation && <div className='rounded border p-3'><h2 className='font-semibold'>Validation results</h2><p>Hard conflicts: {validation.hard_conflicts?.length||0}</p><ul>{validation.hard_conflicts?.map((x:any)=><li key={x.code}>• {x.message}</li>)}</ul><p>Soft warnings: {validation.soft_warnings?.length||0}</p></div>}<div className='overflow-x-auto rounded border'><table className='w-full text-sm'><thead><tr><th>Date</th><th>Time</th><th>Status</th><th/></tr></thead><tbody>{games.map(g=><tr key={g.id}><td>{formatDisplayDate(g.game_date)}</td><td>{formatDisplayTime(g.kickoff_time)}</td><td>{g.status_code}</td><td>{!isCommunityAdmin && <button className='underline' onClick={()=>{setForm(g);setEditingId(g.id);}}>Edit</button>}</td></tr>)}</tbody></table></div></div>}
